### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by zhoujianqing** [YuJianghao/PhyExam#1]
你好，很喜欢的你项目，想用在我们学校，请问能指点我一下吗？登录账户密码是什么？

**Comment by YuJianghao** [comment]
初始的账户密码应该都是root，不过这个还没做完，是用来学php的，如果真用的话还要考虑好。今天我找时间更新下readme。难得有人看上我代码，嘿嘿😁。ps，预计暑假我会把这个写完，如果你想用的话也可以自己写哈。

**Comment by zhoujianqing** [comment]
谢谢，水平有限，略懂皮毛的我怕是很难能像你弄的那么好，我微信wjzhoujianqing ，邮箱cnzhoujianqing@gmail.com，谢谢收到您的回复！
